ar:
  vacancies:
  - chamber: lower
    district: '44'
    vacant_until: 2026-07-15
fl:
  vacancies:
  - chamber: lower
    district: '113'
    vacant_until: 2026-07-15
ga:
  vacancies:
  - chamber: lower
    district: '130'
    vacant_until: 2026-07-15
  - chamber: lower
    district: '177'
    vacant_until: 2026-07-15
  - chamber: upper
    district: '12'
    vacant_until: 2026-07-15
  - chamber: upper
    district: '7'
    vacant_until: 2026-07-15
hi:
  vacancies:
  - chamber: lower
    district: '28'
    vacant_until: 2026-07-15
la:
  vacancies: []
ma:
  vacancies:
  - chamber: lower
    district: 1st Franklin
    vacant_until: 2026-06-01
  - chamber: lower
    district: 17th Middlesex
    vacant_until: 2026-12-01
me:
  vacancies:
  - chamber: lower
    district: 29
    vacant_until: 2026-05-01
mi:
  vacancies:
  - chamber: upper
    district: 35
    vacant_until: 2026-05-15
mo:
  vacancies:
  - chamber: lower
    district: '95'
    vacant_until: 2026-08-15
  - chamber: lower
    district: '110'
    vacant_until: 2026-08-15
  - chamber: lower
    district: '114'
    vacant_until: 2026-08-15
  - chamber: lower
    district: '149'
    vacant_until: 2026-08-15
  - chamber: lower
    district: '160'
    vacant_until: 2026-08-15
nc:
  vacancies:
  - chamber: upper
    district: '23'
    vacant_until: 2026-07-15
  - chamber: lower
    district: '119'
    vacant_until: 2026-07-15
nd:
  vacancies:
  - chamber: lower
    district: '20'
    vacant_until: 2026-11-04
nh:
  vacancies:
  - chamber: lower
    district: Belknap 2
    vacant_until: 2026-05-30
  - chamber: lower
    district: Belknap 6
    vacant_until: 2027-01-01
  - chamber: lower
    district: Cheshire 1
    vacant_until: 2026-05-30
  - chamber: lower
    district: Coos 5
    vacant_until: 2027-01-01
  - chamber: lower
    district: Hillsborough 1
    vacant_until: 2027-01-01
  - chamber: lower
    district: Hillsborough 24
    vacant_until: 2026-05-30
  - chamber: lower
    district: Hillsborough 29
    vacant_until: 2026-05-30
  - chamber: lower
    district: Hillsborough 43
    vacant_until: 2027-01-01
  - chamber: lower
    district: Rockingham 25
    vacant_until: 2026-05-30
  - chamber: lower
    district: Strafford 12
    vacant_until: 2027-01-01
oh:
  vacancies:
  - chamber: upper
    district: '10'
    vacant_until: 2026-10-10
ok:
  vacancies:
  - chamber: lower
    district: 92
    vacant_until: 2026-06-15
  - chamber: lower
    district: 99
    vacant_until: 2026-06-15
pa:
  vacancies:
  - chamber: lower
    district: 12
    vacant_until: 2026-07-01
  - chamber: lower
    district: 196
    vacant_until: 2026-05-20
tx:
  vacancies:
  - chamber: upper
    district: 4
    vacant_until: 2026-07-30
us:
  vacancies:
  - chamber: lower
    district: CA-1
    vacant_until: 2027-01-01
  - chamber: lower
    district: GA-14
    vacant_until: 2027-01-01
  - chamber: lower
    district: NJ-11
    vacant_until: 2027-01-01
ut:
  vacancies:
  - chamber: lower
    district: 6
    vacant_until: 2027-01-01
wv:
  vacancies: []
