name: Update Database

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-24.04

    steps:
    # Python & dependency installation
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      with:
        enable-cache: true
    - name: Yaml file linting
      run: uvx yamllint==1.38.0 -s .
    - name: install dependencies
      run: uv sync

    - name: people to S3
      run: uv run os-people to-csv --upload
      env:
        OS_PEOPLE_DIRECTORY: ${{ env.GITHUB_WORKSPACE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
